### ISSUE TITLE
Geen preview

### ISSUE THREAD

**Issue by cascer1** [eternalflamez/Movietoascii#1]
[ik zie geen preview](https://www.ducohosting.com/screenshots/WP-Em6XoWP-Em6Xo.png) :(

**Comment by jasperverbeet** [comment]
Ga ik voor je fixen

**Comment by cascer1** [comment]
Is het al gefixt? :D

**Comment by jasperverbeet** [comment]
Geen idee.... haha ik heb geen visual studie meer

Op do 22 sep. 2016 11:45 schreef Cas Eliëns notifications@github.com:

**Comment by eternalflamez** [comment]
Toegevoegd in de laatste versie.

**Comment by cascer1** [comment]
No way 😮

**Comment by eternalflamez** [comment]
Yes way!
